const assert = require('node:assert/strict');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const packages = process.env.DRAFT_BROWSER_PACKAGES || 'C:/Users/chocc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const { chromium } = require(require.resolve('playwright', { paths: [packages] }));
(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  try {
    const page = await browser.newPage({ viewport: { width: 390, height: 844 }, reducedMotion: 'reduce' });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(pathToFileURL(path.resolve(__dirname, '../index.html')).href);
    const state = () => page.evaluate(() => JSON.parse(localStorage.getItem('touchline-auction-v1')).game);
    const noOverflow = async () => assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'No horizontal mobile overflow');
    async function range(id, value) {
      await page.locator('#' + id).evaluate((input, value) => { input.value = value; input.dispatchEvent(new Event('input', { bubbles: true })); }, String(value));
    }
    assert(await page.locator('#setup-screen').isVisible());
    assert.equal(await page.locator('#manager-count').inputValue(), '3');
    assert.equal(await page.locator('[data-manager-name]').count(), 3);
    assert.match(await page.locator('#setup-pool').innerText(), /33 players/);
    await page.locator('[data-manager-name="0"]').fill('Alex');
    await page.locator('[data-manager-name="1"]').fill('Sam');
    await page.locator('[data-manager-name="2"]').fill('Charlie');
    await range('setup-rating-min', 95);
    assert(await page.locator('#start').isDisabled(), 'Impossible positional pools must be blocked');
    await range('setup-rating-min', 40);
    await noOverflow();
    await page.screenshot({ path: path.resolve(__dirname, '../preview-setup-mobile.png'), fullPage: true });
    await page.locator('#start').click();
    assert.equal((await state()).pool.length, 33);
    assert.equal(new Set((await state()).pool.map(entry => entry.id)).size, 33);
    assert.equal(await page.locator('#game-screen input[type="range"]').count(), 0);
    assert.equal(await page.locator('.manager-card').count(), 3);
    await noOverflow();
    await page.screenshot({ path: path.resolve(__dirname, '../preview-auction-mobile.png'), fullPage: true });
    // A reload during animation resumes the selected player without spinning twice.
    await page.locator('#spin').click();
    const revealedId = (await state()).currentId;
    await page.reload(); await page.locator('#resume').click();
    assert.equal((await state()).currentId, revealedId);
    await page.locator('#bid-form').waitFor({ state: 'visible' });
    await page.locator('#pass').click();
    assert.equal((await state()).remaining.length, 33);
    await page.locator('#spin').click();
    await page.locator('#bid-form').waitFor({ state: 'visible' });
    assert.notEqual((await state()).currentId, revealedId);
    await page.locator('[data-buyer="manager-1"]').click();
    await page.locator('#bid-price').fill('101');
    assert(await page.locator('#sell').isDisabled());
    assert.match(await page.locator('#bid-error').innerText(), /only has/);
    await page.locator('#bid-price').fill('0.15');
    assert(await page.locator('#sell').isDisabled());
    await page.locator('#bid-price').fill('11.5');
    await page.screenshot({ path: path.resolve(__dirname, '../preview-reveal-mobile.png'), fullPage: true });
    await page.locator('#sell').click();
    assert.match(await page.locator('[data-manager="manager-1"]').innerText(), /£88.5m/);
    await page.locator('#view-buyer').click();
    await page.locator('[data-slot="0"]').click();
    assert.equal((await state()).managers[0].board[0], (await state()).sales[0].playerId);
    assert.equal(await page.locator('.slot-price').innerText(), '£11.5m');
    await page.locator('[data-unplace]').click();
    assert.equal((await state()).sales.length, 1, 'Unplacing must retain the purchase');
    await page.locator('[data-owned]').click(); await page.locator('[data-slot="10"]').click();
    await page.locator('button[data-view="auction"]').click();
    await page.locator('#undo').click();
    assert.equal((await state()).sales.length, 0);
    assert.match(await page.locator('[data-manager="manager-1"]').innerText(), /£100m/);
    assert((await state()).managers[0].board.every(id => id === null));
    await page.locator('#sell').click();
    await page.locator('#next-player').click(); await page.locator('#bid-form').waitFor({ state: 'visible' });
    await page.locator('[data-buyer="manager-2"]').click();
    await page.locator('#bid-price').fill('20'); await page.locator('#sell').click();
    await page.locator('button[data-view="transfers"]').click();
    const transferPrices = await page.locator('.transfer-price').allTextContents();
    assert.deepEqual(transferPrices, ['£20m', '£11.5m']);
    assert.match(await page.locator('.transfer-owner').first().innerText(), /Sam/);
    await page.locator('#ratings-toggle').uncheck();
    assert.equal(await page.locator('#reveal-rating').innerText(), '?');
    assert.equal(await page.locator('#team-average').innerText(), 'Hidden');
    assert((await page.locator('.transfer-meta').allTextContents()).every(text => !text.includes('OVR')));
    await page.screenshot({ path: path.resolve(__dirname, '../preview-transfers-mobile.png'), fullPage: true });
    const beforeReload = await state();
    await page.reload(); await page.locator('#resume').click();
    assert.deepEqual(await state(), beforeReload);
    assert(!(await page.locator('#ratings-toggle').isChecked()));
    await page.locator('#open-settings').click();
    await page.locator('#manager-count').selectOption('8');
    assert.equal(await page.locator('[data-manager-name]').count(), 8);
    await page.locator('#resume').click();
    assert.equal((await state()).config.managerCount, 3, 'Pending setup edits cannot change a resumed auction');
    await page.locator('#open-settings').click();
    await page.locator('#setup-show-ratings').check();
    await page.locator('#start').click();
    assert.equal((await state()).sales.length, 0);
    // Complete a real 33-player auction through the UI.
    for (let i = 0; i < 33; i++) {
      await page.locator(i === 0 ? '#spin' : '#next-player').click();
      await page.locator('#bid-form').waitFor({ state: 'visible' });
      await page.locator(`[data-buyer="manager-${i % 3 + 1}"]`).click();
      await page.locator('#bid-price').fill('1');
      await page.locator('#sell').click();
    }
    const completed = await state();
    assert.equal(completed.phase, 'complete'); assert.equal(completed.remaining.length, 0);
    assert.equal(completed.sales.length, 33);
    for (const manager of completed.managers) assert.equal(completed.sales.filter(sale => sale.managerId === manager.id).length, 11);
    assert(await page.locator('#completion').isVisible());
    await page.locator('#review-teams').click();
    await page.locator('[data-owned]').first().click(); await page.locator('[data-slot="1"]').click();
    const owned = (await state()).managers[2].board[1];
    assert(owned);
    await page.locator('[data-owned]').nth(1).click(); await page.locator('[data-slot="1"]').click();
    assert.notEqual((await state()).managers[2].board[1], owned);
    assert.equal(await page.locator('.slot-price').innerText(), '£1m');
    await noOverflow();
    await page.screenshot({ path: path.resolve(__dirname, '../preview-team-mobile.png'), fullPage: true });
    for (const width of [320, 430]) { await page.setViewportSize({ width, height: 844 }); await noOverflow(); }
    await page.setViewportSize({ width: 1440, height: 1100 });
    await page.locator('button[data-view="auction"]').click();
    await page.screenshot({ path: path.resolve(__dirname, '../preview-auction-desktop.png'), fullPage: true });
    await page.locator('#undo-final').click();
    assert.equal((await state()).phase, 'revealed'); assert.equal((await state()).sales.length, 32);
    await page.locator('#sell').click();
    await page.locator('button[data-view="transfers"]').click();
    assert.equal(await page.locator('.transfer-row').count(), 33);
    assert.deepEqual(errors, []);
    console.log('Browser checks passed: 33-player auction, mobile layouts at 320/390/430px, budgets, price validation, pass, undo, free placement, rating visibility, sorted transfers, locked settings, animation recovery and save/resume.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
